### ISSUE TITLE
Pre-selected filter options are not retained in pagination

### ISSUE THREAD

**Issue by AstCommodore** [tpwd/ke_search#126]
Hello folks!

I have to reopen an old issue from https://github.com/teaminmedias-pluswerk/ke_search/issues/422 :

> When I use pre-selected filter options the search results are displayed as expected. But when switching to another page (pagebrowser), the filter setting is lost.
 
- TYPO3: 11.5.16, Composer
- Extension Version: 4.4.5
- Filter: Predefined select option

When I deactivate my `RoutEnhancer` configuration, the pagination works again. My configuration follows the documentation – so long, but may be, I have made a mistake or there is a bug in the pagination view helper?

```
routeEnhancers:
  # https://docs.typo3.org/p/teaminmedias-pluswerk/ke_search/3.4/en-us/Configuration/RoutingSpeakingUrls.html
  KeSearch:
    type: Plugin
    routePath: '{page}/{filter_1}/{filter_2}/{filter_3}/{filter_4}/{filter_5_58}/{filter_5_57}/{filter_5_56}/{filter_5_55}/{filter_5_54}/{filter_5_53}/{filter_5_183}/{sword}'
    namespace: 'tx_kesearch_pi1'
    defaults:
#      sortByField: 'score'
#      sortByDir: 'desc'
      page: '1'
      sword: ''
      filter_1: ''
      filter_2: ''
      filter_3: ''
      filter_4: ''
      filter_5_58: ''
      filter_5_57: ''
      filter_5_56: ''
      filter_5_55: ''
      filter_5_54: ''
      filter_5_53: ''
      filter_5_183: ''
    requirements:
#      sortByField: '(score|title|sortdate)?'
#      sortByDir: '(asc|desc)?'
      page: '\d+'
      filter_1: '[A-Za-z0-9_/&+-]*'
      filter_2: '[A-Za-z0-9_/&+-]*'
      filter_3: '[A-Za-z0-9_/&+-]*'
      filter_4: '[A-Za-z0-9_/&+-]*'
      filter_5_58: '[A-Za-z0-9_/&+-]*'
      filter_5_57: '[A-Za-z0-9_/&+-]*'
      filter_5_56: '[A-Za-z0-9_/&+-]*'
      filter_5_55: '[A-Za-z0-9_/&+-]*'
      filter_5_54: '[A-Za-z0-9_/&+-]*'
      filter_5_53: '[A-Za-z0-9_/&+-]*'
      filter_5_183: '[A-Za-z0-9_/&+-]*'
    aspects:
#      sortByField:
#        type: StaticValueMapper
#        map:
#          score: 'score'
#          title: 'title'
#          sortdate: 'sortdate'
#      sortByDir:
#        type: StaticValueMapper
#        map:
#          asc: 'asc'
#          desc: 'desc'
      page:
        type: StaticRangeMapper
        start: '1'
        end: '99'
      filter_1:
        type: KeSearchTagToSlugMapper
      filter_2:
        type: KeSearchTagToSlugMapper
      filter_3:
        type: KeSearchTagToSlugMapper
      filter_4:
        type: KeSearchTagToSlugMapper
      filter_5_58:
        type: KeSearchTagToSlugMapper
      filter_5_57:
        type: KeSearchTagToSlugMapper
      filter_5_56:
        type: KeSearchTagToSlugMapper
      filter_5_55:
        type: KeSearchTagToSlugMapper
      filter_5_54:
        type: KeSearchTagToSlugMapper
      filter_5_53:
        type: KeSearchTagToSlugMapper
      filter_5_183:
        type: KeSearchTagToSlugMapper
      sword:
        type: KeSearchUrlEncodeMapper

```
